### ISSUE TITLE
Lag when switching between files

### ISSUE THREAD

**Issue by samu** [xndcn/symbols-tree-view#36]
Hey there, cool package, thanks for creating it.

I have a small problem though. I notice a very slight lag when switching between opened files. Maybe thats just because my computer is too slow, and it's just a couple of milliseconds, but it is noticeable. I assume that lag might be caused from loading the symbol list again, each time a view gets activated. Would it be possible to extract that logic into a promise and lazily display the tree view?

**Comment by xndcn** [comment]
@samu Sorry about that... In fact, loading symbol list is using promise, but maybe parsing symbols make it slow... I will try to fix it, thanks!

**Comment by xndcn** [comment]
@samu I found that the `lag` is mainly due to creating `dom` of tree-view... Sorry but now I don't have ideas how to optimize it...

**Comment by samu** [comment]
@xndcn i'll close this one as i haven't had the problem with recent releases of atom.

**Comment by johnyf** [comment]
Could you please reopen this issue? It persists for me. For example, when switching to a pane with the file https://github.com/johnyf/openpromela/blob/8a74b37b2b481cb9b1914fd9b2b4b38bb8162a73/openpromela/logic.py, or when saving this file. It takes 3 seconds or so until the editor unfreezes. This problem is similar to https://github.com/7ute/symbols-list/issues/36. Perhaps modifying an existing `dom`, instead of recreating it can solve this issue.
